# Generated by Django 6.0.4 on 2026-06-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='agreement_question',
            field=models.CharField(blank=True, default='', help_text='Optionale Zustimmungsfrage vor dem Artikel (nur im Pro/Contra-Design). Leer lassen für Standardfrage.', max_length=255),
        ),
    ]
