# Generated by Django 6.0.4 on 2026-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0018_alter_configuration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='pro_contra_layout',
            field=models.BooleanField(default=False, help_text="Kommentare in Pro/Contra-Spalten anzeigen (Pro = tag 'pro', Contra = tag 'contra')"),
        ),
    ]
