# Generated by Django 6.0.4 on 2026-04-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0019_configuration_pro_contra_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='start_article_id',
            field=models.IntegerField(blank=True, help_text="Nur relevant wenn Start-Ansicht 'Direkt zu Artikel'. Artikel ID eingeben", null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='start_newspaper_id',
            field=models.IntegerField(blank=True, help_text="Nur relevant wenn Start-Ansicht 'Artikelübersicht' Zeitung ID eingeben", null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='start_view',
            field=models.CharField(choices=[('newspapers', 'Zeitungsübersicht'), ('article_list', 'Artikelübersicht einer Zeitung'), ('article', 'Direkt zu einem Artikel')], default='newspapers', help_text='Wohin werden Versuchspersonen nach den Vor-Fragen weitergeleitet?', max_length=20),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='pro_contra_layout',
            field=models.BooleanField(default=False, help_text='Kommentare in Pro/Contra-Spalten anzeigen'),
        ),
    ]
