# Generated by Django 6.0.4 on 2026-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0020_configuration_start_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='like_dislike_count_visible',
            field=models.BooleanField(default=True, help_text='Zeigt die Like/Dislike-Zähler für die Versuchspersonen an.'),
        ),
    ]
