# Generated by Django 6.0.4 on 2026-07-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0019_commentclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclick',
            name='agreement',
            field=models.CharField(blank=True, choices=[('agree', 'Stimme zu'), ('disagree', 'Stimme nicht zu')], max_length=10, null=True),
        ),
    ]
