# Generated by Django 6.0.4 on 2026-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0017_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='side',
            field=models.CharField(blank=True, choices=[('pro', 'Pro'), ('contra', 'Contra'), ('neutral', 'Neutral')], default='neutral', max_length=10),
        ),
    ]
