# Generated by Django 6.0.4 on 2026-04-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0018_comment_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='side',
            field=models.CharField(blank=True, choices=[('pro', 'Pro'), ('contra', 'Contra')], max_length=10),
        ),
    ]
