# Generated by Django 6.0.4 on 2026-06-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0019_alter_comment_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='base_dislikes',
            field=models.IntegerField(default=0, help_text='Vom Admin festgelegte Basis-Anzahl an Dislikes.'),
        ),
        migrations.AddField(
            model_name='comment',
            name='base_likes',
            field=models.IntegerField(default=0, help_text='Vom Admin festgelegte Basis-Anzahl an Likes.'),
        ),
    ]
